syntax = "proto3";

package driver;

option go_package = "shared/proto/driver;driver";

service DriverService{
    rpc RegisterDriver(RegisterRequest) returns (RegisterResponse);
    rpc UnregisterDriver(UnregisterRequest) returns (UnregisterResponse);
    
}

message RegisterRequest{
    string driverId = 1;
    string packageSlug = 2;
}

message RegisterResponse{
    Driver driver = 1;
}

message Driver{
    string userId = 1;
    string name = 2;
    string carNumber = 3;
    string profilePicture = 4;
    string packageSlug = 5;
}

message UnregisterRequest{
    string driverId = 1;
}

message UnregisterResponse{
    Driver driver = 1;   
}