syntax = "proto3";

package trip;

option go_package = "shared/proto/trip;trip";

service TripService{
    rpc PreviewTrip(PreviewTripRequest) returns (PreviewTripResponse);

}

message PreviewTripRequest {
    string userId = 1;
    Coordinate pickup = 2;
    Coordinate destination = 3;
}

message PreviewTripResponse {
    string tripId = 1;
    Route route = 2;
    repeated RideShare rideFares = 3;
}

message Coordinate {
    double latitute = 1;
    double longitude = 2;
}

message Route {
    double distance = 1;
    double duration = 2;
    string polyline = 3;
}

message RideShare {
    string id = 1;
    string userId = 2;
    string packageSlug = 3;
    double totalPrice = 4;
    
}